import type { ReactNode } from 'react'
import { FlowMark } from './Brand'

type AuthLayoutProps = { children: ReactNode; eyebrow: string; title: string; description: string }

export function AuthLayout({ children, eyebrow, title, description }: AuthLayoutProps) {
  return <main className='min-h-svh bg-canvas p-4 text-ink sm:grid sm:place-items-center sm:p-8'><div className='mx-auto grid min-h-[calc(100svh-2rem)] max-w-5xl overflow-hidden rounded-xl border border-line bg-surface sm:min-h-0 sm:grid-cols-[1.05fr_.95fr]'><section className='relative hidden overflow-hidden border-r border-line bg-surface-raised p-10 sm:flex sm:flex-col'><FlowMark /><div className='my-auto max-w-sm'><p className='mb-4 text-xs font-medium uppercase tracking-[0.18em] text-accent'>Telegram automation</p><h1 className='text-3xl font-semibold tracking-tight text-ink'>Build flows with clarity.</h1><p className='mt-4 text-sm leading-6 text-muted'>A focused workspace for shaping the conversations your Telegram bot can handle.</p></div><FlowDecoration /><p className='text-xs text-muted'>Webilo Flow · v0.1</p></section><section className='flex min-w-0 items-center px-5 py-8 sm:px-10 sm:py-12'><div className='mx-auto w-full max-w-sm'><div className='mb-8 sm:hidden'><FlowMark /></div><p className='text-xs font-medium uppercase tracking-[0.16em] text-accent'>{eyebrow}</p><h1 className='mt-3 text-2xl font-semibold tracking-tight text-ink'>{title}</h1><p className='mt-2 text-sm leading-6 text-muted'>{description}</p><div className='mt-7'>{children}</div></div></section></div></main>
}

function FlowDecoration() { return <svg aria-hidden='true' className='absolute bottom-16 right-8 h-48 w-72 text-line' fill='none' viewBox='0 0 288 192'><path d='M45 39h69l48 48h76M45 153l69-36 48-30h76M114 39v78' stroke='currentColor' strokeWidth='1.25' /><rect fill='#11161D' height='28' rx='6' stroke='#7C3AED' width='58' x='16' y='25' /><rect fill='#11161D' height='28' rx='6' stroke='currentColor' width='58' x='85' y='103' /><rect fill='#11161D' height='28' rx='6' stroke='currentColor' width='58' x='209' y='73' /><circle cx='114' cy='39' fill='#7C3AED' r='3' /><circle cx='162' cy='87' fill='#7C3AED' r='3' /></svg> }
